name: main
on:
  push:
    branches:
    - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push container image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit:${{ github.sha }}
    - name: Checkout prod
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.GH_ORG }}/devspace-vcluster-argocd-prod
        persist-credentials: false
        fetch-depth: 0
    - name: Update manifests
      run: |
        sleep 1
        cat production/devops-toolkit.yaml | sed -e "s@- ${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit:.*@- ${{ secrets.DOCKERHUB_USERNAME }}/devops-toolkit:${{ github.sha }}@g" | tee production/devops-toolkit.yaml
        git config --global user.email "${{ secrets.GH_ORG }}@farcic.com"
        git config --global user.name "${{ secrets.GH_ORG }}"
        git add .
        git commit -m "Promoting devops-toolkit ${{ github.sha }}"
    - name: Push prod
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        repository: ${{ secrets.GH_ORG }}/devspace-vcluster-argocd-prod
 